version: "3"
services:
  snitch:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./src/:/usr/src/app/src/
    restart: always
    networks:
      - dupbit_prime
networks:
  dupbit_prime:
    external: true
